plugins:
  - jekyll-paginate

# Site settings
title: One Mo' Gin
email: cory@onemogin.com
description: > # this means to ignore newlines until "baseurl:"
  &copy; Cory Watson. All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onemogin.com" # the base hostname & protocol for your site
#twitter_username: gphat
github_username:  gphat
linkedin_username: gphat
title_image: "http://onemogin.com/assets/images/cory-noggin.jpeg"
paginate: 5

# outputting
permalink: none

# Build settings
markdown: kramdown
highlighter: rouge
